version: '3'
services:
  postgresql:
    image: postgres:latest
    volumes:
      - ./database/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rekindle_dev
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: IAmThouThouArtI
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    ports:
      - 6379:6379
