version: '3'
services:
  postgresql:
    image: postgres:latest
    volumes:
      - ./database/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rekindle_dev
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: IAmThouThouArtI
    ports:
      - 5432:5432

  redis-cache:
    image: redis:latest
    ports:
      - 6379:6379

  rabbit:
    image: rabbitmq:3.8-rc-management
    environment:
      RABBITMQ_DEFAULT_USER: developer
      RABBITMQ_DEFAULT_PASS: IAmThouThouArtI
    ports:
      - 5672:5672
      - 15672:15672
