version: '3'
services:
  postgresql:
    image: postgres:latest
    volumes:
      - ./database/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rekindle_dev
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: IAmThouThouArtI
    ports:
      - 5432:5432

  mongo:
    image: mongo:latest
    volumes:
      - ./database/mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: IAmThouThouArtI
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: developer
      ME_CONFIG_MONGODB_ADMINPASSWORD: IAmThouThouArtI
    ports:
      - 8081:8081

  redis:
    image: redis:latest
    ports:
      - 6379:6379
